development:
  COINBASE_APP_KEY: 'XkzFolrOCYFMmYvL'
  COINBASE_APP_SECRET: 'LbOWKtrp19yP990j7HUI03Jh7fTf0x4Z'

test:
  COINBASE_APP_KEY: 'XkzFolrOCYFMmYvL'
  COINBASE_APP_SECRET: 'LbOWKtrp19yP990j7HUI03Jh7fTf0x4Z'

production:
  COINBASE_APP_KEY: 'XkzFolrOCYFMmYvL'
  COINBASE_APP_SECRET: 'LbOWKtrp19yP990j7HUI03Jh7fTf0x4Z'
